clear;

% Create test function mappings
run('test_functions');

% The gamultiobj_test_map var contains function handles that run the
% gamultiobj() function for the test function with the given options
test_fn = gamultiobj_test_map('kursawe');

options = gaoptimset(...
    'Generations', 100, ...
    'PopulationSize', 500, ...
    'Vectorized', 'on', ...
    'PlotFcn', @gaplotpareto, ...
    'Display', 'off' ...
);

test_fn(options);