addpath('../test_functions/');

% Mapping of test function names to structs that describe corresponding
% optimization parameters
test_function_map = containers.Map(...
    {'schaffer', 'fonsecafleming', 'kursawe'}, ...
    { ...
        struct( ...
            'n', 1, ...
            'fn', @schaffer, ...
            'lb', -10, ...
            'ub', 10, ...
            'utopia', [0 0] ...
        ), ...
        struct( ...
            'n', 3, ...
            'fn', @fonsecafleming, ...
            'lb', [-4 -4 -4], ...
            'ub', [4 4 4], ...
            'utopia', [0 0] ...
        ), ...
        struct( ...
            'n', 3, ...
            'fn', @kursawe, ...
            'lb', [-5 -5 -5], ...
            'ub', [5 5 5], ...
            'utopia', [-20 -11.627286837] ...
        ) ...
    } ...
);
